import { Padauk } from "next/font/google";
import "@/app/globals.css";

const padauk = Padauk({ 
  subsets: ["latin"],
  weight: ["400", "700"],
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={padauk.className}>{children}</body>
    </html>
  );
}
