import { Padauk } from "next/font/google";
import "@/app/globals.css";
import DashboardHeader from "@/components/dashboard/Header";

const padauk = Padauk({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Popken Digital Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
      <body className={padauk.className}>
        <DashboardHeader />
        {children}
      </body>
    </html>
  );
}
